[2025-08-05 14:42:29,670][root][INFO] - Initializing Tokenizer
[2025-08-05 14:42:29,671][root][INFO] - Initializing Task
[2025-08-05 14:42:29,675][root][ERROR] - Error locating target 'torch_seq_moo.tasks.nupack.NupackTask', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
Traceback (most recent call last):
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'torch_seq_moo.tasks' has no attribute 'nupack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/aya/GFN_for_mRNA_design/MOGFN/mo_gfn/torch_seq_moo/tasks/nupack.py", line 7, in <module>
    from nupack import Strand, Complex, ComplexSet, Model, SetSpec, complex_analysis
ModuleNotFoundError: No module named 'nupack'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'torch_seq_moo.tasks.nupack.NupackTask':
ModuleNotFoundError("No module named 'nupack'")
Are you sure that 'nupack' is importable from module 'torch_seq_moo.tasks'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/aya/GFN_for_mRNA_design/MOGFN/mo_gfn/main.py", line 60, in main
    task = hydra.utils.instantiate(config.task, tokenizer=tokenizer)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'torch_seq_moo.tasks.nupack.NupackTask', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
[2025-08-05 14:42:57,261][root][INFO] - Initializing Tokenizer
[2025-08-05 14:42:57,262][root][INFO] - Initializing Task
[2025-08-05 14:42:57,265][root][ERROR] - Error locating target 'mo_gfn.torch_seq_moo.tasks.nupack.NupackTask', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
Traceback (most recent call last):
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'mo_gfn.torch_seq_moo.tasks' has no attribute 'nupack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/aya/GFN_for_mRNA_design/MOGFN/mo_gfn/torch_seq_moo/tasks/nupack.py", line 7, in <module>
    from nupack import Strand, Complex, ComplexSet, Model, SetSpec, complex_analysis
ModuleNotFoundError: No module named 'nupack'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'mo_gfn.torch_seq_moo.tasks.nupack.NupackTask':
ModuleNotFoundError("No module named 'nupack'")
Are you sure that 'nupack' is importable from module 'mo_gfn.torch_seq_moo.tasks'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/aya/GFN_for_mRNA_design/MOGFN/mo_gfn/main.py", line 60, in main
    task = hydra.utils.instantiate(config.task, tokenizer=tokenizer)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/ubuntu/ENTER/envs/mo_env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'mo_gfn.torch_seq_moo.tasks.nupack.NupackTask', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
